name: Test workflow

inputs:
    test:
        required: false

runs:
    using: "composite"
    steps:
        - name: testing
          shell: bash
          run: |
            echo $GITHUB_ACTION_PATH
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
        - name: run script
          shell: bash
          run: |
            python $GITHUB_ACTION_PATH/scripts/main.py