name: Test workflow

inputs:
    test:
        required: false

runs:
    using: "composite"
    steps:
        - name: testing
          shell: bash
          run: |
            echo $GITHUB_ACTION_PATH
        - name: Setup Python
          uses: anzx/cosmos-github-actions/setup-python@main
          with:
            python-version: '3.x'
            setup-poetry: 'true'
        - name: run script
          shell: bash
          run: |
            python $GITHUB_ACTION_PATH/scripts/main.py