name: Test workflow
on:
    workflow_call:
    workflow_dispatch:

jobs:
    test-job:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Test step
              run: echo "Hello world"