name: Test workflow
on:
    workflow_call:
    workflow_dispatch:
        inputs:
            env:
                type: string
                default: "d"

jobs:
    test-job:
        runs-on: ubuntu-latest
        environment: ${{ inputs.env }}ev
        steps:
            - name: Test step
              run: |
                echo ${{ github.event.repository.name }}
                echo ${{ github.ref_name }}
                echo ${{ github.repository }}